# Generated by Django 5.2.3 on 2025-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(blank=True, null=True, upload_to='carteles/'),
        ),
    ]
